/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import Dao.clsCargoDao;
import Dao.clsPersonaDao;
import Modelo.Espacio_Estacionamiento;
import Modelo.PersonaMod;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

public class Asistencia extends javax.swing.JInternalFrame {

	clsPersonaDao dao = new clsPersonaDao();
	clsCargoDao cargdao = new clsCargoDao();
	PersonaMod pers = new PersonaMod();
	Espacio_Estacionamiento estac = new Espacio_Estacionamiento();

	public Asistencia() {
		initComponents();
		txtLugar.setEnabled(false);
		cargdao.spaceAvailables();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                txtdniMarcacion = new javax.swing.JTextField();
                jScrollPane1 = new javax.swing.JScrollPane();
                tableSpaces = new javax.swing.JTable();
                txtLugar = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();

                setClosable(true);

                jLabel1.setText("N° DNI:");

                txtdniMarcacion.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                txtdniMarcacionKeyPressed(evt);
                        }
                });

                tableSpaces.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {},
                                {},
                                {},
                                {}
                        },
                        new String [] {

                        }
                ));
                tableSpaces.setCellSelectionEnabled(true);
                jScrollPane1.setViewportView(tableSpaces);
                tableSpaces.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

                txtLugar.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyPressed(java.awt.event.KeyEvent evt) {
                                txtLugarKeyPressed(evt);
                        }
                });

                jLabel2.setText("Lugar:");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(46, 46, 46)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2))
                                                .addGap(32, 32, 32)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtdniMarcacion, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtdniMarcacion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void txtdniMarcacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdniMarcacionKeyPressed
		if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
			String dni = txtdniMarcacion.getText().trim();

			if (dni.length() == 8) {
				pers.setDNI(dni);

				if (dao.hasActiveEntry(dni)) {
					dao.exitParking(pers);
					cargdao.spaceAvailables();
					// Cierra la ventana actual
					//this.dispose();
				} else {
					txtLugar.setEnabled(true); // Habilita el campo para elegir lugar
					txtLugar.requestFocus();
				}
			} else {
				JOptionPane.showMessageDialog(null, "Ingrese un DNI válido (8 dígitos).");
			}
		}
        }//GEN-LAST:event_txtdniMarcacionKeyPressed

        private void txtLugarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLugarKeyPressed
		if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
			String dni = txtdniMarcacion.getText().trim();
			String textoLugar = txtLugar.getText().trim();

			if (!textoLugar.isEmpty()) {
				try {
					int idEspacio = Integer.parseInt(textoLugar);
					pers.setDNI(dni);
					Espacio_Estacionamiento espacio = new Espacio_Estacionamiento();
					espacio.setIDESPACIO(idEspacio);

					dao.chooseParking(pers, espacio);
					cargdao.spaceAvailables();

					// Cierra la ventana después de registrar
					//this.dispose();

				} catch (NumberFormatException e) {
					JOptionPane.showMessageDialog(null, "ID de espacio inválido.");
				} catch (Exception e) {
					JOptionPane.showMessageDialog(null, "Error al ingresar: " + e.getMessage());
				}
			}
		}
        }//GEN-LAST:event_txtLugarKeyPressed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JScrollPane jScrollPane1;
        public static javax.swing.JTable tableSpaces;
        private javax.swing.JTextField txtLugar;
        private javax.swing.JTextField txtdniMarcacion;
        // End of variables declaration//GEN-END:variables
}
