/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

//internal jFrame
import Dao.clsCargoDao;
import Dao.clsPersonaDao;
import Modelo.PersonaMod;
import javax.swing.JOptionPane;

//internal jframe
public class frmPersona extends javax.swing.JInternalFrame {

	/**
	 * Creates new form frmPersona
	 */
	PersonaMod pers = new PersonaMod(); //props persona table
	clsPersonaDao dao = new clsPersonaDao();
	clsCargoDao cargDao = new clsCargoDao();

	public frmPersona() {
		initComponents();
		cmbCargo.removeAllItems();
		dao.llenarCargo();
		cargDao.ListarPersonas();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jTabbedPane1 = new javax.swing.JTabbedPane();
                jPanel2 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                txtBuscar = new javax.swing.JTextField();
                btnBuscar = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                tbPersonal = new javax.swing.JTable();
                jPanel1 = new javax.swing.JPanel();
                txtape = new javax.swing.JTextField();
                btnActualizar = new javax.swing.JButton();
                btnRegistro = new javax.swing.JButton();
                txtdni = new javax.swing.JTextField();
                txtnom = new javax.swing.JTextField();
                txttelf = new javax.swing.JTextField();
                cmbCargo = new javax.swing.JComboBox<>();
                btnEliminar = new javax.swing.JButton();
                jButton6 = new javax.swing.JButton();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                txtclave = new javax.swing.JTextField();

                jLabel1.setText("Nombre del Personal:");

                txtBuscar.setText("jTextField1");

                btnBuscar.setText("Buscar");
                btnBuscar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBuscarActionPerformed(evt);
                        }
                });

                tbPersonal.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {},
                                {},
                                {},
                                {}
                        },
                        new String [] {

                        }
                ));
                tbPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tbPersonalMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(tbPersonal);

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel1)
                                .addGap(120, 120, 120)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(btnBuscar)
                                .addContainerGap(220, Short.MAX_VALUE))
                        .addComponent(jScrollPane1)
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnBuscar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                jTabbedPane1.addTab("Listado de Personal", jPanel2);

                btnActualizar.setText("Actualizar");
                btnActualizar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnActualizarActionPerformed(evt);
                        }
                });

                btnRegistro.setText("Registrar");
                btnRegistro.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRegistroActionPerformed(evt);
                        }
                });

                cmbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                btnEliminar.setText("Eliminar");
                btnEliminar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnEliminarActionPerformed(evt);
                        }
                });

                jButton6.setText("Salir");
                jButton6.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton6ActionPerformed(evt);
                        }
                });

                jLabel2.setText("DNI:");

                jLabel3.setText("Nombre:");

                jLabel4.setText("Apellidos:");

                jLabel6.setText("Telefono:");

                jLabel7.setText("Cargo:");

                jLabel8.setText("Clave:");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3))
                                                .addGap(37, 37, 37)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtdni, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                                        .addComponent(txtnom))
                                                .addGap(47, 47, 47)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel7))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(cmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtape, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(49, 49, 49)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(jButton6))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txtclave, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel6)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addGap(133, 133, 133)
                                                                        .addComponent(jLabel5))
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addGap(35, 35, 35)
                                                                        .addComponent(txttelf, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addContainerGap(113, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(txtape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnRegistro))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnActualizar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnEliminar)
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel5))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(76, 76, 76)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel7)
                                                        .addComponent(cmbCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(30, 30, 30)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(txttelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(txtclave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(116, 116, 116)
                                .addComponent(jButton6)
                                .addGap(43, 43, 43))
                );

                jTabbedPane1.addTab("Registro del Personal", jPanel1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane1)
                                .addGap(33, 33, 33))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
                //datos vacios
		if (txtBuscar.getText().equals("")) {
			//txtBuscar.requestFocus();
			cargDao.ListarPersonas();
			return;
		}
		pers.setDNI(txtBuscar.getText());
		dao.BuscarPersonalDao(pers);
        }//GEN-LAST:event_btnBuscarActionPerformed

        private void tbPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPersonalMouseClicked
		if (tbPersonal.getSelectedRow() != -1) {
			int fila = tbPersonal.getSelectedRow();
			this.txtdni.setText(tbPersonal.getValueAt(fila, 0).toString());
			this.txtnom.setText(tbPersonal.getValueAt(fila, 1).toString());
			this.txtape.setText(tbPersonal.getValueAt(fila, 2).toString());
			this.txttelf.setText(tbPersonal.getValueAt(fila, 3).toString());
			//llena comboBox con cargos disponibles
			this.cmbCargo.setSelectedItem(tbPersonal.getValueAt(fila, 4));
			//despues de hacer click cambia de pestaña
			jTabbedPane1.setSelectedIndex(1);
		}
        }//GEN-LAST:event_tbPersonalMouseClicked

        private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        }//GEN-LAST:event_jButton6ActionPerformed

        private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
                //datos vacios
		if (txtdni.getText().equals("")) {
			JOptionPane.showMessageDialog(null, "No olvide ingresar los datos", "Aviso", JOptionPane.INFORMATION_MESSAGE);
			txtdni.requestFocus();
			return;
		}

		pers.setDNI(txtdni.getText());
		pers.setNOMBRE(txtnom.getText());
		pers.setAPELLIDOS(txtape.getText());
		pers.setTELF(txttelf.getText());
		pers.setIDCARGO(cmbCargo.getSelectedIndex());
		pers.setCLAVE(txtclave.getText());
		dao.registrarPersonal(pers);
        }//GEN-LAST:event_btnRegistroActionPerformed

        private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
		if (txtdni.getText().equals("")) {
			JOptionPane.showMessageDialog(null, "No olvide ingresar los datos", "Aviso", JOptionPane.INFORMATION_MESSAGE);
			txtdni.requestFocus();
			return;
		}
		pers.setDNI(txtdni.getText());
		pers.setNOMBRE(txtnom.getText());
		pers.setAPELLIDOS(txtape.getText());
		pers.setTELF(txttelf.getText());
		pers.setIDCARGO(cmbCargo.getSelectedIndex());
		pers.setCLAVE(txtclave.getText());
		dao.actualizarPersonal(pers);
        }//GEN-LAST:event_btnActualizarActionPerformed

        private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
		if (txtdni.getText().equals("")) {
			JOptionPane.showMessageDialog(null, "Para eliminar no olvide seleccionar una fila", "Aviso", JOptionPane.INFORMATION_MESSAGE);
			txtdni.requestFocus();
			return;
		}
		pers.setDNI(txtdni.getText());
		dao.eliminarPersonal(pers);
        }//GEN-LAST:event_btnEliminarActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnActualizar;
        private javax.swing.JButton btnBuscar;
        private javax.swing.JButton btnEliminar;
        private javax.swing.JButton btnRegistro;
        public static javax.swing.JComboBox<String> cmbCargo;
        private javax.swing.JButton jButton6;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTabbedPane jTabbedPane1;
        public static javax.swing.JTable tbPersonal;
        private javax.swing.JTextField txtBuscar;
        private javax.swing.JTextField txtape;
        private javax.swing.JTextField txtclave;
        private javax.swing.JTextField txtdni;
        private javax.swing.JTextField txtnom;
        private javax.swing.JTextField txttelf;
        // End of variables declaration//GEN-END:variables
}
